steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args: ['-c', 'ls -A1 | xargs rm -rf;git clone $$COMPONENT_GITURL .;git checkout --track -b $BRANCH_NAME origin/$BRANCH_NAME;env | sed "s/^/export /" >> /workspace/cloudbuild.sh']
    env: 
      - 'COMPONENT_GITURL=https://github.com/ortelius/ortelius'
      - 'COMPONENT_VERSION=9.0.0'
      - 'COMPONENT_DOCKERREPO=quay.io/ortelius/ortelius'
      - 'BLDDATE=`date`'
      - 'IMAGE_TAG="$BRANCH_NAME-v$$COMPONENT_VERSION.$$(git rev-list --count $BRANCH_NAME)-g$SHORT_SHA"'

  # Login to Quay for push.
  # PASSWORD is decrypted before this step runs.
  # Note: You need a shell to resolve environment variables with $$
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    env:
      - 'DOCKER_CONFIG=/workspace/docker-config'
    args: ['-c', '. /workspace/cloudbuild.sh;docker login quay.io --username "$$QUAY_USERID" --password $$QUAY_PASSWORD']
    secretEnv: ['QUAY_USERID', 'QUAY_PASSWORD']     

  # Build deployhub-webadmin.war - quay.io/ortelius/ortelius
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ["-c", '. /workspace/cloudbuild.sh;docker build --tag "$$COMPONENT_DOCKERREPO:$$IMAGE_TAG" -f /workspace/docker/Dockerfile .']
     
  # Push the image to Quay.
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    env:
      - 'DOCKER_CONFIG=/workspace/docker-config'
    args: ['-c', ". /workspace/cloudbuild.sh;docker push $$COMPONENT_DOCKERREPO:$$IMAGE_TAG"]

  # Set component name and tag 
  - name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args: ['-c', 'env | sed "s/^/export /" >> /workspace/cloudbuild.sh']
    env: 
      - 'COMPONENT_DOCKERREPO=quay.io/ortelius/ms-general'

  # Build dh-ms-general.war - quay.io/ortelius/ms-general
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ["-c", '. /workspace/cloudbuild.sh;docker build --tag "$$COMPONENT_DOCKERREPO:$$IMAGE_TAG" -f /workspace/docker/DockerfileGeneral .']
     
  # Push the image to Quay.
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    env:
      - 'DOCKER_CONFIG=/workspace/docker-config'
    args: ['-c', ". /workspace/cloudbuild.sh;docker push $$COMPONENT_DOCKERREPO:$$IMAGE_TAG"]

  # Set component name and tag 
  - name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args: ['-c', 'env | sed "s/^/export /" >> /workspace/cloudbuild.sh']
    env: 
      - 'COMPONENT_DOCKERREPO=quay.io/ortelius/ms-ui'

  # Build dh-ms-general.war - quay.io/ortelius/ms-ui
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ["-c", '. /workspace/cloudbuild.sh;docker build --tag "$$COMPONENT_DOCKERREPO:$$IMAGE_TAG" -f /workspace/docker/DockerfileUI .']
     
  # Push the image to Quay.
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    env:
      - 'DOCKER_CONFIG=/workspace/docker-config'
    args: ['-c', ". /workspace/cloudbuild.sh;docker push $$COMPONENT_DOCKERREPO:$$IMAGE_TAG"]

  # Set component name and tag 
  - name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args: ['-c', 'env | sed "s/^/export /" >> /workspace/cloudbuild.sh']
    env: 
      - 'COMPONENT_DOCKERREPO=quay.io/ortelius/ms-nginx'

  # Build dh-ms-general.war - quay.io/ortelius/ms-nginx
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ["-c", '. /workspace/cloudbuild.sh;docker build --tag "$$COMPONENT_DOCKERREPO:$$IMAGE_TAG" -f /workspace/docker/DockerfileNginx .']
     
  # Push the image to Quay.
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    env:
      - 'DOCKER_CONFIG=/workspace/docker-config'
    args: ['-c', ". /workspace/cloudbuild.sh;docker push $$COMPONENT_DOCKERREPO:$$IMAGE_TAG"]

secrets:
- kmsKeyName: projects/eighth-physics-169321/locations/global/keyRings/cli/cryptoKeys/quay
  secretEnv:
    QUAY_USERID: CiQAW+P1J9UZz+Hr1uonladAW2dKqaiVd5ux8Q9EV81pK0u5V+4SNACcBdnKacvH4QXPamH1N4uJZvZ/0TMwvELgXAAlP0wR2zBw2WhCV82GMiUkW3iGVlbqz7c=
- kmsKeyName: projects/eighth-physics-169321/locations/global/keyRings/cli/cryptoKeys/quay-pw
  secretEnv:
    QUAY_PASSWORD: CiQAUULEud9Ej8XtwNAb9gkbDVhSGFZYhUGE30fNwR+7ehAOkH8SMgCz6KYeykjgS16RPxgKlrIQL/1TKDt06v4OXGIisFXOkdWC+jvdda8mTzVNCi8sT5g6 
  